Fix panic in query tracing (#9024)
## Describe your changes
<!--- An in-depth description of the changes made by this PR. Technical details and possible side effects. -->

I had a issue where Diesel was unable to build an update query, but this is how it manifested:
```
  2024-04-04T23:48:54.361231Z ERROR tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ApiError(Database(DbInteract(Panic(Any { .. }))))
```
The panic stack trace said:

```
thread 'tokio-runtime-worker' panicked at library/alloc/src/fmt.rs:612:32:
a formatting trait implementation returned an error: Error
stack backtrace:
   0:        0x1090d52bc - std::backtrace_rs::backtrace::libunwind::trace::hd3c0154278411ba9
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:        0x1090d52bc - std::backtrace_rs::backtrace::trace_unsynchronized::h7e868fa4f72c0d0a
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1090d52bc - std::sys_common::backtrace::_print_fmt::h7babef1c71141ed7
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x1090d52bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3be43c6214e69043
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1090f7e84 - core::fmt::rt::Argument::fmt::he26861354a677178
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/fmt/rt.rs:142:9
   5:        0x1090f7e84 - core::fmt::write::h12f9049830901a82
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/fmt/mod.rs:1120:17
   6:        0x1090d1ed0 - std::io::Write::write_fmt::h2ff514dfe799c882
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/io/mod.rs:1846:15
   7:        0x1090d50f0 - std::sys_common::backtrace::_print::h359885544b9d612b
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1090d50f0 - std::sys_common::backtrace::print::h722d6ff0889d39c2
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x1090d6a94 - std::panicking::default_hook::{{closure}}::hd7f9985c1b9ae0aa
  10:        0x1090d67dc - std::panicking::default_hook::h29fb35819c2a32ca
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:292:9
  11:        0x102d5165c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h01a43c02e49f75b7
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2029:9
  12:        0x102d51c24 - <sentry_panic::PanicIntegration as sentry_core::integration::Integration>::setup::{{closure}}::{{closure}}::h45530a0e0abef6ec
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sentry-panic-0.31.5/src/lib.rs:71:17
  13:        0x1090d7008 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h93b7b92139b91f09
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2029:9
  14:        0x1090d7008 - std::panicking::rust_panic_with_hook::h401df0236a0e7dae
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:785:13
  15:        0x1090d6dc4 - std::panicking::begin_panic_handler::{{closure}}::h67f4ee7322151c3c
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:659:13
  16:        0x1090d5740 - std::sys_common::backtrace::__rust_end_short_backtrace::hbce128a2ff88406e
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:171:18
  17:        0x1090d6b4c - rust_begin_unwind
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
  18:        0x1091d03cc - core::panicking::panic_fmt::hecc1dfe94cb15bc7
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
  19:        0x1091d080c - core::result::unwrap_failed::h5e7f249f3c140ed3
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1649:5
  20:        0x1090ecf48 - core::result::Result<T,E>::expect::h8da855525fcf8dd9
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1030:23
  21:        0x1090ecf48 - alloc::fmt::format::format_inner::h7e53fb4fd59bb4c4
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/fmt.rs:612:9
  22:        0x108ab0c7c - alloc::fmt::format::{{closure}}::h233338c2ae552691
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/fmt.rs:616:34
  23:        0x108aa8d2c - core::option::Option<T>::map_or_else::h53e2952d793c5b99
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/option.rs:1173:21
  24:        0x10737fab8 - alloc::fmt::format::h5dfe7c48fe9197aa
                               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/fmt.rs:616:5
  25:        0x1073838cc - <tracing_opentelemetry::layer::SpanAttributeVisitor as tracing_core::field::Visit>::record_debug::h3064d1134fd617db
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-opentelemetry-0.19.0/src/layer.rs:354:60
  26:        0x106917160 - <tracing_core::field::DisplayValue<T> as tracing_core::field::Value>::record::h89923af1b2983f84
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/field.rs:682:9
  27:        0x108f93874 - <&T as tracing_core::field::Value>::record::hac2d96af6ab839bf
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/field.rs:594:9
  28:        0x108f93d8c - tracing_core::field::ValueSet::record::hd1765b1932dfa83b
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/field.rs:1006:17
  29:        0x108f8b910 - tracing_core::span::Attributes::record::h96fe85e26e4d2789
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/span.rs:183:9
  30:        0x103bedcdc - <tracing_opentelemetry::layer::OpenTelemetryLayer<S,T> as tracing_subscriber::layer::Layer<S>>::on_new_span::h57b0fc7ec9be0e02
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-opentelemetry-0.19.0/src/layer.rs:723:9
  31:        0x103919b6c - <alloc::boxed::Box<dyn tracing_subscriber::layer::Layer<S>+core::marker::Send+core::marker::Sync> as tracing_subscriber::layer::Layer<S>>::on_new_span::h38006c4fe1bc4bec
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.14/src/layer/mod.rs:1583:17
  32:        0x103af67c0 - <alloc::vec::Vec<L> as tracing_subscriber::layer::Layer<S>>::on_new_span::h4076482285b4c227
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.14/src/layer/mod.rs:1703:17
  33:        0x103915af4 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::new_span::h062b85197432cdd9
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.14/src/layer/layered.rs:128:9
  34:        0x108f7eddc - tracing_core::dispatcher::Dispatch::new_span::h2ee4359fe68839c3
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/dispatcher.rs:561:9
  35:        0x108f809e8 - tracing::span::Span::make_with::h3d0696952cf082b7
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:569:18
  36:        0x108f8086c - tracing::span::Span::new_with::hca4e7b0a70262192
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:448:9
  37:        0x108f80814 - tracing::span::Span::new::{{closure}}::h8a4ec76fbc0b18eb
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:437:44
  38:        0x108f7e45c - tracing_core::dispatcher::get_default::h479e11bfa1be30df
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/dispatcher.rs:391:16
  39:        0x108f807d0 - tracing::span::Span::new::ha9cd26e94957a751
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:437:9
  40:        0x106c60088 - <db::instrumented_connection::InstrumentedPgConnection as diesel::connection::LoadConnection>::load::h53077cfaba600784
                               at /Users/ethan/src/monorepo/backend/components/db/core/src/instrumented_connection.rs:181:5
  41:        0x1062f9d78 - <T as diesel::query_dsl::load_dsl::LoadQuery<Conn,U,B>>::internal_load::h044ba77849001644
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.0.2/src/query_dsl/load_dsl.rs:76:21
  42:        0x1062f6398 - diesel::query_dsl::RunQueryDsl::get_result::h0e3a92ac5bce1926
                               at /Users/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.0.2/src/query_dsl/mod.rs:1681:15
  43:        0x106a84a08 - db::models::partner_tenant::PartnerTenant::update::h3cdcd39ac0b17755
                               at /Users/ethan/src/monorepo/backend/components/db/core/src/models/partner_tenant.rs:118:22
...
```

It seems our query instrumentation is returning an error which is being `expect`ed here: https://github.com/rust-lang/rust/blob/1.77.0/library/alloc/src/fmt.rs#L612C40-L612C91.

I adjusted the `DebugQuery` `Display` impl to not return an error so a `format!` doesn't panic. This is an odd behavior in Rust that `Display::fmt` is a panic risk.

After this change, this is how the error shows up:
```
  2024-04-04T23:52:45.663755Z ERROR tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ApiError(Database(DbError(QueryBuilderError("There are no changes to save. This query cannot be built"))))
  ```

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->