Fix stytch deser (#5044)
## Describe your changes

Right now we parse the stytch response `reasons` as an Enum and if its
Unknown it becomes `Unknown(String)`. If we then reserialize this
struct, it will serialize that as `{"Unknown": "Thingie"}` which then
means if we try to reredesrialize we will get an error like `invalid
type: map, expected a string`.
We actually don't strictly have a use case for doing this because we
always read the cyphertext vendor response which does not go through
deser but its still nice to ensure deser -> ser -> desr works to prevent
future pain

## Issue: <FP-???>

## Caveats

<!--- Are there any caveats to this changeset? -->

## Test Plan

```
thread 'stytch::response::tests::parse_success::example_response2_expects_action_challenge_vec_reason_knowndatacenterip_reason_unknown_string_from_something_else_yo_' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a string", line: 0, column: 0)', components/idv/src/stytch/response.rs:136:77
```