[Coba] 'Dangling' zip because user was unable to edit empty field (#5884)
## Describe your changes

One of coba users was running into a bug where they couldn't edit the
zip field. They deleted the input but couldn't add it in again,
resulting in errors "Vaulting data on kyc confirm page failed: Unable to
generate a valid request data obj because of incomplete/dangling DIs.
Error: Dangling DIs: id.zip"

[Session Recording on
LogRocket](https://app.logrocket.com/lrswdg/footprint-bifrost-prod/s/5-7ae36fb9-ada3-4de5-8fb1-d6b0af462fb4/0?dashboardID=logrocket-overview&filters=%255B%257B%2522id%2522%253A%2522Sk7CTZZxp%2522%252C%2522type%2522%253A%2522userID%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522899b1137-c62d-4cbe-8c8d-abd1fa464e7e%2522%255D%257D%255D&fromTab=&persistForm=true&t=1695779074302.2678)

**Old behavior:**
- user is unable to edit zip code once saved to state machine
- user is unable to delete zip and state fields


https://github.com/onefootprint/monorepo/assets/18564210/ee51ed1d-4eda-4b33-a802-0b6a5c78112b

**New behavior:**

We don't have masks for international zip codes:

https://github.com/onefootprint/monorepo/assets/18564210/9b4f8630-c4ac-45e1-a80c-811243d3c2d5

We also now replaced the masks with validations in US zip codes for the
time being - we will revisit this again for a better solution:

https://github.com/onefootprint/monorepo/assets/18564210/c314fbe7-2383-42e2-9d45-fad9823e8924

<!--- An in-depth description of the changes made by this PR. Technical
details and possible side effects.

Example:
- before/after screenshots (if appropriate).
- Sample payloads (if it's a API change).
- Changes x feature to such that y
- Added x
- Removed y -->

## Issue: <FP-???>

## Caveats

<!--- Are there any caveats to this changeset? -->

## Test Plan

<!--- How did you test your changes? :) -->