Set statement_timeout=3s for Diesel migrations (#8172)
## Describe your changes
<!--- An in-depth description of the changes made by this PR. Technical
details and possible side effects. -->
Here's how it behaves on a migration that sleeps for 10 seconds:

```
[2024-02-13T22:28:32Z INFO  db] Running migrations
thread 'main' panicked at /Users/ethan/src/monorepo/backend/components/api/core/src/state.rs:224:50:
failed to run migrations: MigrationFailed(QueryError(DieselMigrationName { name: "2024-02-13-222255_testing-slow", version: MigrationVersion("20240213222255") }, DatabaseError(Unknown, "canceling statement due to statement timeout")))
stack backtrace:
   0:        0x1089b0650 - std::backtrace_rs::backtrace::libunwind::trace::hddb53f9645107e69
                               at 
// snip
  47:        0x100ae14a8 - _main
make[1]: *** [run-enclave-local] Terminated: 15
make: *** [run-local] Terminated: 15
[1]    89862 terminated  make run-local

```

The API server fails to start up. This means we'd catch slow migrations
when an ECS rolling deploy fails.

## Caveats
<!--- Are there any caveats to this changeset? -->

## Test Plan
<!--- How did you test your changes? -->

<!---
### Frontend/Design Checklist
- Can we add any unit tests? What about E2E tests?
- Do we need to notify any customers?
- Do we need to update any developer docs?
- If doing SDK changes
    - Are they backwards compatible?
    - Which NPM packages do we need to release, and when?
- Are there any performance implications? What does the lighthouse
output show?

### Screenshots / videos (attachment)
- [ ] IDV
  - [ ] Mobile & Desktop
  - [ ] Bifrost & Hosted & Handoff
  - [ ] Integration with SDKs + appearance customizations
- [ ] Dashboard
- [ ] Form
  - [ ] Different variants/fields
 -->