Fix bulk_get_vdr_blob_keys_active_at query to disambiguate multiple historically-active DLs for a DI (#12998)
## Describe your changes
I found some consistency issues in VDR on dev:

```
AssertionError: VDR data and API data mismatch for fp_id_y02FqELIyGnf9KZRVvoYLT at version 4
Mismatch in API Data: [('id.dob', None), ('id.ssn9', '120981234')]
Mismatch in VDR Data: [('id.dob', '1995-12-25'), ('id.ssn9', '127650713')]
```

The `id.ssn9` in VDR's version 4 here is the true version 3 `id.ssn9`.
This is because at version 4, both the v3 and v4 `id.ssn9` are active.
This is possible only for data that was created before the
`unique_active_data_lifetime_per_scoped_vault_kind` constraint was
created.

We can confirm this with the following query:
```
WITH counts AS (
	SELECT
		dl.scoped_vault_id,
		dl.kind,
		dl.created_seqno,
		(
			SELECT
				count(*)
			FROM
				data_lifetime dl2
			WHERE
				dl2.scoped_vault_id = dl.scoped_vault_id
				AND dl2.kind = dl.kind
				AND dl2.created_seqno <= dl.created_seqno
				AND (dl2.deactivated_seqno IS NULL
					OR dl2.deactivated_seqno > dl.created_seqno)) num_active_dls
		FROM
			data_lifetime dl
		GROUP BY
			dl.scoped_vault_id,
			dl.created_seqno,
			dl.kind
)
SELECT
	*, (select max(created_at) from data_lifetime dl where dl.scoped_vault_id = counts.scoped_vault_id and dl.kind = counts.kind and dl.created_seqno = counts.created_seqno) as timestamp
FROM
	counts where num_active_dls > 1;
```

In dev, all DL timestamps are in 2023, well before that constraint was
added.

This PR updates VDR query to match the vault wrapper behavior which
gives precedence to newer DLs if there are multiple active for a given
DI at a given seqno. This will require backfillin


## Caveats


## Test Plan