Fix MockEnclave test flakiness (#3088)
## Describe your changes

Sometimes we get failing tests in CI because parallel running tests are
both calling `StateWithMockEnclave::init()` and picking the same ports.
```
thread 'task::tests::watchlist_check_task::onboarding_pending' panicked at 'failed to build enclave proxy server: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', components/api/core/src/utils/mock_enclave.rs:45:14
```
eg:
https://github.com/onefootprint/monorepo/actions/runs/4692673804/jobs/8318677257

Fixes this by wrapping the port picking in a static mutex

## Issue: <FP-???>

## Caveats

<!--- Are there any caveats to this changeset? -->

## Test Plan

<!--- How did you test your changes? :) -->