Force drop test db (#4017)
## Describe your changes

Started getting a lot of 
```
failures:

---- decision::state::kyc::tests::valid_action stdout ----
CREATED TEST DB: test_db_9aa91ebdb0994062b257bbba17b065b9
load .env at: /home/runner/work/monorepo/monorepo/backend/.env
DROPPING TEST DB: test_db_9aa91ebdb0994062b257bbba17b065b9
thread 'decision::state::kyc::tests::valid_action' panicked at 'failed to drop test db: DatabaseError(Unknown, "database \"test_db_9aa91ebdb0994062b257bbba17b065b9\" is being accessed by other users")', components/db/src/tests/test_db_pool.rs:80:14
```

in
[CI](https://github.com/onefootprint/monorepo/actions/runs/5334944374/jobs/9667453431#step:11:378)
so seeing if this helps.

I think it's fine just to break connections since this is test DB so
didn't look into printing what process/user is still accessing the db
but could go that route if necessary

## Issue: <FP-???>

## Caveats

<!--- Are there any caveats to this changeset? -->

## Test Plan

wait and see :fingers-crossed: