[FP-4306] Extract API error from selfie into retryable failure reason (#3660)
## Describe your changes

Some errors from incode come in the form of an HTTP error instead of an HTTP 200. This catches _one_ of them :)

## Caveats

Definitely doesn't catch all errors, and definitely could be a better supported pattern instead of needing the state machine to know intricacies of error implementations

## Test Plan

Sent back image as selfie locally and tested that we extracted into a retry 

```
---- decision::vendor::incode::test::test_run_machine_dl::true_expects stdout ----
CREATED TEST DB: test_db_6b93220a139448f6837e9562518de050
load .env at: /Users/elliott/fp/monorepo/backend/.env
[SelfieFaceNotFound]
thread 'decision::vendor::incode::test::test_run_machine_dl::true_expects' panicked at 'assertion failed: failure_reasons.is_empty()', components/api/core/src/decision/vendor/incode/test.rs:134:5
```